version: '3.5'

networks:
  tdin-net:
    driver: bridge

services:
  express-app:
    build: ./central-server
    container_name: central-server
    volumes:
      - "./central-server/src/:/app/src/"
      - "./central-server/bin/:/app/bin/"
    working_dir: /app
    networks:
      - tdin-net
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:latest
    restart: always
    networks:
      - tdin-net
    ports:
      - "27017:27017"

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    networks:
      - tdin-net
